# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#source 'http://BlanBok:MbWQy8Xs@git.coding.net/BlanBok/WKSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'ExampleProjectDemo' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!
    
    pod 'AFNetworking'                        #网络请求
    pod 'WKDataManager'                       #网络请求AFNetworking二次封装
#
    pod 'Masonry'                             #设置约束
#    pod 'MJRefresh'                           #scrollview上下拉刷新
#    pod 'SAMKeychain'                          #钥匙串访问存储账户密码
#    pod 'UITableView+FDTemplateLayoutCell'    #uitableviewcell获取cell高度
    
    pod 'Aspects'                             #进行AOP进行编程
    pod 'ReactiveObjC'                        #通过RAC简化响应式编程

#    pod 'YYModel'                             #数据模型转换
#    pod 'SDWebImage'                          #图片的异步加载
#    pod 'MBProgressHUD'                       #加载动画
#    pod 'CLImageEditor'                       #图片编辑/仅做使用参考 基于CoreImage的封装
#    pod 'WKCategory', :git=> 'https://github.com/Blanbok/WKCategory' #一些类的常用拓展方法

#    pod 'YYKeyboardManager'                   #键盘监听
#    pod 'TTRangeSlider'                       #自定义silder
#    pod 'MagicalRecord'                       #coreData使用第三方
#    pod 'ICarousel'                           #旋转木马效果
#    pod 'SDCycleScrollView'                   #轮播图
#    pod 'CocoaLumberjack'                     #更高级的 log 功能

    pod 'PTPageRouter', :git=> 'https://github.com/OComme/PT-PageRouter'  #页面跳转规范

end
